<?php

$labels = array(
    'columns'		=> 'MULTIPLE COLUMNS',
    'headline'		=> '- Headline',
    'text'			=> '- Text',
    'text_columns'	=> '- mehrspaltige Texte',
    'image'			=> '- Single image',
    'image_list'	=> '- multiple linkable images/texts',
    'button'		=> '- Button',
    'content_list'	=> '- Linkliste',
    'gallery'		=> '- Bildergalerie',
    'downloads'		=> '- Downloads',
    'line'			=> '- Trennlinie',
    'video'			=> '- Video',
    'shortcode'		=> '- Shortcode',
    'tables'		=> '- Tabelle',
    'formulare'		=> '- Formular',
    'flex'			=> '- Flexible field',
    'extra_menu'	=> '- Men&uuml;',
    'empty'			=> '- Leerinhalt',
    'wall'			=> '- Content-Wall',
    'articles'		=> '- Article (wall or slider)',
    '360grad'		=> '- 360 Grad Objekt',
    'showreel'		=> '- Showreel',
);


$c = array(
    'inactive'			=> array(
        'label'				=> 'Inactive',
        'instructions'		=> 'only visible if logged',
        'name'				=> 'inactive',
        'key'				=> 'inactive',
        'type'				=> 'true_false',
        'default_value'		=> false,
        
    ),
    'view' 				=> array(
    	'label'				=> 'View',
    	'name'				=> 'view',
    	'key'				=> 'view',
    	'type'				=> 'select',
    	'choices'			=> $individole['choices_module_view'],
    	'default_value'		=> 'full',
    ),
    'top'				=> array(
        'label'				=> 'Space top',
        'name'				=> 'top',
        'key'				=> 'top',
        'type'				=> 'number',
        'default_value'		=> 0,
    ),
    'bottom'			=> array(
        'label'				=> 'Space bottom',
        'name'				=> 'bottom',
        'key'				=> 'bottom',
        'type'				=> 'number',
        'default_value'		=> 0,
    ),
    //'inset' 				=> array(
    //	'label'				=> 'Gap left/right',
    //	'name'				=> 'inset',
    //	'key'				=> 'inset',
    //	'type'				=> 'select',
    //	'choices'			=> $individole['choices_module_inset'],
    //	'default_value'		=> 'full',
    //),
    //'column_gaps'		=> array(
	//	'label'				=> 'Column gaps',
	//	'name'				=> 'column_gaps',
    //    'key'				=> 'column_gaps',
    //    'type'				=> 'select',
    //    'default_value'		=> 0,
    //    'choices'			=> $individole['choices_module_column_gaps'],
	//),
	'left'				=> array(
        'label'				=> 'Abstand links',
        'name'				=> 'left',
        'key'				=> 'left',
        'type'				=> 'select',
        'default_value'		=> 0,
        'choices'			=> $individole['choices_gap'],
    ),
    'right'				=> array(
        'label'				=> 'Abstand rechts',
        'name'				=> 'right',
        'key'				=> 'right',
        'type'				=> 'select',
        'default_value'		=> 0,
        'choices'			=> $individole['choices_gap'],
    ),
    'column_gap'		=> array(
        'label'				=> 'Abstand Spalten',
        'name'				=> 'column_gap',
        'key'				=> 'column_gap',
        'type'				=> 'select',
        'default_value'		=> 'default',
        'choices'			=> $individole['choices_gap_columns'],
    ),
    'grid'				=> array(
        'label'				=> 'Spaltenraster',
        'name'				=> 'grid',
        'key'				=> 'grid',
        'type'				=> 'select',
        'default_value'		=> 'default',
        'choices'			=> $individole['choices_grid'],
    ),
    //'post_type'			=> array(
    //    'label'				=> 'Post Type',
    //    'name'				=> 'post_type',
    //    'key'				=> 'post_type',
    //    'type'				=> 'select',
    //    'default_value'		=> '',
    //    'choices'			=> $individole['choices_post_types'],
    //),
    'background'		=> array(
        'label'				=> 'Background',
        'name'				=> 'background',
        'key'				=> 'background',
        'type'				=> 'color_picker',
        'default_value'		=> '',
    ),
    'box'				=> array(
        'label'				=> 'Box',
        'name'				=> 'box',
        'key'				=> 'box',
        'type'				=> 'true_false',
        'default_value'		=> 'false',
    ),
    'columns'		=> array(
	    'label'				=> '# Spalten',
	    'name'				=> 'columns',
	    'key'				=> 'columns',
	    'type'				=> 'select',
	    'default_value'		=> 12,
	    'choices'			=> $individole['module_columns'],
	),
);

?>