<?php

$m_360grad = $m_2_360grad = array(
			'label'				=> $labels['360grad'],
			'name'				=> 'm_360grad',
			'key'				=> 'm_360grad',
			'type'				=> 'repeater',
			'instructions'		=> '',
			'display'			=> 'row',
			'sub_fields'		=> array(
				'config_base'		=> $config_base_360grad,
				'm_360grad_options' => array(
				    'label'				=> 'Einstellungen',
				    'name'				=> 'm_360grad_options',
				    'key'				=> 'm_360grad_options',
				    'type'				=> 'repeater',
				    'layout'			=> 'row',
				    'row_limit' 		=> 1,
				    'row_min' 			=> 1,
				    'column_width'		=> 80,
				    'sub_fields'		=> array(
				    	'mouseover' 		=> array(
				    		'label'				=> 'Mouseover',
				    		'name'				=> 'mouseover',
				    		'key'				=> 'mouseover',
				    		'type'				=> 'true_false',
				    	),
				    	'loop' 				=> array(
				    		'label'				=> 'Loop',
				    		'name'				=> 'loop',
				    		'key'				=> 'loop',
				    		'type'				=> 'true_false',
				    	),
				    	'indicator' 		=> array(
				    		'label'				=> 'Positionsanzeiger',
				    		'instructions'		=> 'H&ouml;he in Pixel',
				    		'name'				=> 'indicator',
				    		'key'				=> 'indicator',
				    		'type'				=> 'number',
				    	),
				    	'speed' 			=> array(
				    		'label'				=> 'Geschwindigkeit',
				    		'name'				=> 'speed',
				    		'key'				=> 'speed',
				    		'type'				=> 'number',
				    		'default_value'		=> 3,
				    	),
				    ),
				),
				'm_360grad_images' => array(
					'label'				=> 'Bilder',
					'button_label'		=> '+ Bild hinzuf&uuml;gen',
					'name'				=> 'm_360grad_images',
					'key'				=> 'm_360grad_images',
					'type'				=> 'repeater',
					'layout'			=> 'table',
					'row_limit' 		=> 0,
					'row_min' 			=> 0,
					'sub_fields'		=> array(
						'image_1' 			=> array(
							'label'				=> 'Basis-Bild (1. Frame)',
							'name'				=> 'image_1',
							'key'				=> 'image_1',
							'type'				=> 'image',
							'preview_size'		=> 'medium',
							'save_format'		=> 'id',
							'column_width'		=> 40,
						),
						'image_2' 			=> array(
							'label'				=> 'Bildsequenz',
							'instructions'		=> 'Einzelbild mit allen Frames im Uhrzeigersinn',
							'name'				=> 'image_2',
							'key'				=> 'image_2',
							'type'				=> 'image',
							'preview_size'		=> 'medium',
							'save_format'		=> 'id',
							'column_width'		=> 40,
						),
						'frames' 			=> array(
				    		'label'				=> '# Frames',
				    		'name'				=> 'frames',
				    		'key'				=> 'frames',
				    		'type'				=> 'number',
				    		'default_value'		=> 36,
				    		'column_width'		=> 20,
				    	),
					),
				),
			),
		);