<?php

$choices_pages = getAdminPosts("page");
$choices_kunde = getAdminPosts("kunde");

$choices_all_posts = $choices_pages + $choices_kunde;

$m_image_list = $m_2_image_list = array(
			'label'				=> $labels['image_list'],
			'name'				=> 'm_image_list',
			'key'				=> 'm_image_list',
			'display'			=> 'row',
			'sub_fields'		=> array(
				'config_base'		=> $config_base_image_list,
				'm_image_list_options' => array(
					'label'				=> 'Listen-<br>einstellungen',
					'name'				=> 'm_image_list_options',
					'key'				=> 'm_image_list_options',
					'type'				=> 'repeater',
					'layout'			=> 'table',
					'row_limit' 		=> 1,
					'row_min' 			=> 1,
					'sub_fields'		=> array(
						'configs_base'		=> array(
							'label'				=> 'Grundeinstellungen',
							'name'				=> 'configs_base',
							'key'				=> 'configs_base',
							'type'				=> 'repeater',
							'layout'			=> 'row',
							'row_limit' 		=> 1,
							'row_min' 			=> 1,
							'column_width'		=> 60,
							'sub_fields'		=> array(
								'text' 				=> array(
									'label'				=> 'Textanzeige / Typ',
									'name'				=> 'text',
									'key'				=> 'text',
									'type'				=> 'select',
									'choices'			=> $individole['choices_imagelist_text'],
									'default'			=> 'below',
								),
								'text_title' 		=> array(
									'label'				=> 'Textanzeige / Title',
									'name'				=> 'text_title',
									'key'				=> 'text_title',
									'type'				=> 'true_false',
								),
								'text_subtitle' 	=> array(
									'label'				=> 'Textanzeige / Subtitle',
									'name'				=> 'text_subtitle',
									'key'				=> 'text_subtitle',
									'type'				=> 'true_false',
								),
								'text_text' 		=> array(
									'label'				=> 'Textanzeige / Text',
									'name'				=> 'text_text',
									'key'				=> 'text_text',
									'type'				=> 'true_false',
								),
								'gap'				=> array(
									'label'				=> 'Abstand Bilder',
									'name'				=> 'gap',
									'key'				=> 'gap',
									'type'				=> 'select',
									'choices'			=> $individole['choices_gap_columns'],
									'default_value'		=> 'default',
								),
								'per_row'			=> array(
									'label'				=> 'Bilder pro Reihe',
									'name'				=> 'per_row',
									'key'				=> 'per_row',
									'type'				=> 'select',
									'choices'			=> $individole['choices_image_list_per_row'],
									'default_value'		=> '3',
								),
								'scale'				=> array(
									'label'				=> 'Skalierung',
									'name'				=> 'scale',
									'key'				=> 'scale',
									'type'				=> 'select',
									'choices'			=> $individole['choices_image_list_scale'],
									'default_value'		=> '1.0',
								),
								'overlay_bg_color'	=> array(
									'label'				=> 'Text-Overlay / Hintergrundfarbe',
									'name'				=> 'overlay_bg_color',
									'key'				=> 'overlay_bg_color',
									'type'				=> 'color_picker',
								),
								'overlay_bg_opacity'=> array(
									'label'				=> 'Text-Overlay / Deckkraft',
									'instructions'		=> '(1-100)',
									'name'				=> 'overlay_bg_opacity',
									'key'				=> 'overlay_bg_opacity',
									'type'				=> 'number',
									'default_value'		=> '0',
								),
								'overlay_position'	=> array(
									'label'				=> 'Text-Overlay / Position',
									'instructions'		=> 'neg. Wert f&uuml;r Positionierung von unten',
									'name'				=> 'overlay_position',
									'key'				=> 'overlay_position',
									'type'				=> 'number',
									'default_value'		=> '10',
								),
								'shadow'			=> array(
									'label'				=> 'Bildschatten',
									'name'				=> 'shadow',
									'key'				=> 'shadow',
									'type'				=> 'true_false',
								),
								
							),
						),
						'configs_canvas'		=> array(
							'label'				=> 'Einstellungen Canvas',
							'name'				=> 'configs_canvas',
							'key'				=> 'configs_canvas',
							'instructions'		=> 'Bilder in Rahmen einpassen, Standard quadratisch oder Breite/H&ouml;he angeben (Seitenverh&auml;ltnis reicht)',
							'type'				=> 'repeater',
							'layout'			=> 'row',
							'row_limit' 		=> 1,
							'row_min' 			=> 1,
							'column_width'		=> 40,
							'sub_fields'		=> array(
								'status'			=> array(
									'label'				=> 'An/Aus',
									'name'				=> 'status',
									'key'				=> 'status',
									'type'				=> 'true_false',
								),
								'canvas_w'			=> array(
									'label'				=> 'Breite',
									'name'				=> 'canvas_w',
									'key'				=> 'canvas_w',
									'type'				=> 'number',
									'default_value'		=> '0',
								),
								'canvas_h'			=> array(
									'label'				=> 'H&ouml;he',
									'name'				=> 'canvas_h',
									'key'				=> 'canvas_h',
									'type'				=> 'number',
									'default_value'		=> '0',
								),
								'background'	=> array(
									'label'				=> 'Hintergrund',
									'name'				=> 'background',
									'key'				=> 'background',
									'type'				=> 'color_picker',
								),
							),
						),
					),
				),
				'm_image_list_images' => array(
					'label'				=> 'Bilder',
					'button_label'		=> '+ Bild hinzuf&uuml;gen',
					'name'				=> 'm_image_list_images',
					'key'				=> 'm_image_list_images',
					'type'				=> 'repeater',
					'layout'			=> 'table',
					'row_limit' 		=> 0,
					'row_min' 			=> 0,
					'sub_fields'		=> array(
						'image' 			=> array(
							'label'				=> 'Bild',
							'name'				=> 'image',
							'key'				=> 'image',
							'type'				=> 'image',
							'preview_size'		=> 'medium',
							'save_format'		=> 'id',
							'column_width'		=> 15,
						),
						'options' 			=> array(
							'label'				=> 'Einstellungen',
							'name'				=> 'options',
							'key'				=> 'options',
							'type'				=> 'repeater',
							'layout'			=> 'row',
							'row_limit' 		=> 1,
							'row_min' 			=> 1,
							'column_width'		=> 85,
							'sub_fields'		=> array(
								'link_intern' 		=> array(
									'label'				=> 'Interner Link',
									'name'				=> 'link_intern',
									'key'				=> 'link_intern',
									'type'				=> 'select',
									'choices'			=> $choices_all_posts,
									'allow_null'		=> '1',
								),
								'link_extern' 		=> array(
									'label'				=> 'oder externer Link',
									'name'				=> 'link_extern',
									'key'				=> 'link_extern',
									'type'				=> 'text',
									'formatting'		=> 'none',
								),
								'zoom' 				=> array(
									'label'				=> 'oder Zoom',
									'name'				=> 'zoom',
									'key'				=> 'zoom',
									'type'				=> 'true_false',
								),
								'title' 			=> array(
									'label'				=> 'Title',
									'name'				=> 'title',
									'key'				=> 'title',
									'type'				=> 'text',
									'formatting'		=> 'html',
								),
								'subtitle' 			=> array(
									'label'				=> 'Subtitle',
									'name'				=> 'subtitle',
									'key'				=> 'subtitle',
									'type'				=> 'text',
									'formatting'		=> 'html',
								),
								'text' 				=> array(
									'label'				=> 'Text',
									'name'				=> 'text',
									'key'				=> 'text',
									'type'				=> 'textarea',
									'formatting'		=> 'html',
								),
							),
						),
					),
				),
			),
		);